# Generated by Django 2.1 on 2018-09-05 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('series', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('purchase_price', models.IntegerField()),
                ('engine_size', models.IntegerField()),
                ('fuel_system', models.CharField(max_length=50)),
                ('tank_capacity', models.IntegerField()),
                ('power', models.IntegerField()),
                ('seating_capacity', models.IntegerField()),
                ('transmission', models.CharField(max_length=10)),
                ('body_type', models.CharField(max_length=30)),
                ('drive', models.CharField(max_length=3)),
                ('wheelbase', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('occupation', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pickup_date', models.DateField()),
                ('return_date', models.DateField(blank=True)),
                ('carID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basesite.Car')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basesite.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('QLD', 'Queensland'), ('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('ACT', 'Australian Capital Territory'), ('TAS', 'Tasmania'), ('SA', 'South Australia'), ('WA', 'Western Australia'), ('NT', 'Northen Territory')], max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_store', to='basesite.Store'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_store',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_store', to='basesite.Store'),
        ),
    ]
