# Generated by Django 2.1 on 2018-09-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basesite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
