# Generated by Django 2.1 on 2018-09-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basesite', '0003_auto_20180907_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
