# Generated by Django 2.1 on 2018-09-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basesite', '0004_auto_20180907_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_size',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
