# Generated by Django 2.1 on 2018-09-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basesite', '0005_auto_20180907_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unavailable',
            field=models.BooleanField(default=False),
        ),
    ]
